# Generated by Django 5.0.2 on 2024-02-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='category',
            new_name='theme',
        ),
    ]
