# Generated by Django 5.0.2 on 2024-02-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_category_word_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='project.theme'),
        ),
    ]
